superproductgroups_display_form:
  path: /superproductgroups/display-form
  methods: [GET]
  defaults:
    _controller: '\PrestaShop\Module\SuperProductGroups\Controller\Admin\SuperProductGroupsController::displayForm'

superproductgroups_handle_form_submit:
  path: /superproductgroups/handle-form-submit
  methods: [POST]
  defaults:
    _controller: '\PrestaShop\Module\SuperProductGroups\Controller\Admin\SuperProductGroupsController::handleFormSubmit'

superproductgroups_save_group_products:
  path: /superproductgroups/save-group-products
  methods: [POST]
  defaults:
    _controller: '\PrestaShop\Module\SuperProductGroups\Controller\Admin\SuperProductGroupsController::saveGroupProducts'

superproductgroups_delete_group:
  path: /superproductgroups/delete-group
  methods: [POST]
  defaults:
    _controller: '\PrestaShop\Module\SuperProductGroups\Controller\Admin\SuperProductGroupsController::deleteGroup'

superproductgroups_delete_group_product:
  path: /superproductgroups/delete-group-product
  methods: [POST]
  defaults:
    _controller: '\PrestaShop\Module\SuperProductGroups\Controller\Admin\SuperProductGroupsController::deleteGroupProduct'

superproductgroups_delete_group_products:
  path: /superproductgroups/delete-group-products
  methods: [POST]
  defaults:
    _controller: '\PrestaShop\Module\SuperProductGroups\Controller\Admin\SuperProductGroupsController::deleteGroupProducts'

superproductgroups_ajax_products:
  path: /superproductgroups/ajax-products
  methods: [GET]
  defaults:
    _controller: '\PrestaShop\Module\SuperProductGroups\Controller\Admin\SuperProductGroupsController::ajaxProducts'

superproductgroups_ajax_group_products:
  path: /superproductgroups/ajax-group-products
  methods: [GET]
  defaults:
    _controller: '\PrestaShop\Module\SuperProductGroups\Controller\Admin\SuperProductGroupsController::ajaxGroupProducts'

superproductgroups_ajax_groups:
  path: /superproductgroups/ajax-groups
  methods: [GET]
  defaults:
    _controller: '\PrestaShop\Module\SuperProductGroups\Controller\Admin\SuperProductGroupsController::ajaxGroups'

superproductgroups_export_group_products:
  path: /superproductgroups/export-group-products
  methods: [GET]
  defaults:
    _controller: '\PrestaShop\Module\SuperProductGroups\Controller\Admin\SuperProductGroupsController::exportGroupProducts'

# superproductgroups_ajax_check_product_has_groups:
#   path: /superproductgroups/ajax-process-check-product-has-groups
#   defaults:
#     _controller: 'PrestaShop\Module\SuperProductGroups\Controller\Front\GroupProductController::ajaxProcessCheckProductHasGroups'
#   methods: [POST]

# module_superproductgroups_ajax_save_selected_products:
#   path: /superproductgroups/ajax-process-save-selected-products
#   defaults:
#     _controller: 'PrestaShop\Module\SuperProductGroups\Controller\Front\GroupProductController::ajaxProcessSaveSelectedProducts'
#   methods: [POST]

# module_superproductgroups_ajax_get_selected_products:
#   path: /superproductgroups/ajax-process-get-selected-products
#   defaults:
#     _controller: 'PrestaShop\Module\SuperProductGroups\Controller\Front\GroupProductController::ajaxProcessGetSelectedProducts'
#   methods: [POST]

